# -*- coding: utf-8 -*-
"""Adaptive_Food_Suggestion_Engine .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nWR39H52YZyFqgzlLXr5U1g_gIARKgo5
"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

Budget = ctrl.Antecedent(np.arange(0, 300, 1), ' Budget')
Environment = ctrl.Antecedent(np.arange(0, 100.2, 0.1), 'Environment')
Food = ctrl.Consequent(np.arange(0.2, 10.1, 0.1), 'Food')

Budget.automf(3)
Environment.automf(3)

Food['low'] = fuzz.trimf( Food.universe, [0, 0, 4.5])
Food['medium'] = fuzz.trimf( Food.universe, [0, 4.5, 10.0])
Food['high'] = fuzz.trimf( Food.universe, [4.5, 10.0, 10.0])
rule1 = ctrl.Rule( Budget['poor'] | Environment['poor'],  Food['low'])
rule2 = ctrl.Rule(Environment['average'],  Food['medium'])
rule3 = ctrl.Rule(Environment['good'] |  Budget['good'],  Food['high'])

Food_op_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
Food_op = ctrl.ControlSystemSimulation(Food_op_ctrl)
Food_op.input[' Budget'] = 1.3
Food_op.input['Environment'] = 36.7

Food_op.compute()
print (Food_op.output['Food'])
Food.view(sim= Food_op)

pip install scikit-fuzzy