# -*- coding: utf-8 -*-
"""clinical_decision_support_system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dWUXEaMh5Z_DumjOJJdf6aKiN5ZBHXvh
"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

Glycaemia = ctrl.Antecedent(np.arange(0, 3.8, 0.1), 'Glycaemia')
Sirolimus = ctrl.Antecedent(np.arange(20.4, 41.2, 0.1), 'Sirolimus')
Proteinuria = ctrl.Consequent(np.arange(0.2, 9.1, 0.1), 'Proteinuria')

Glycaemia.automf(3)
Sirolimus.automf(3)

Proteinuria['low'] = fuzz.trimf( Proteinuria.universe, [0, 0, 4.5])
Proteinuria['medium'] = fuzz.trimf( Proteinuria.universe, [0, 4.5, 9.0])
Proteinuria['high'] = fuzz.trimf( Proteinuria.universe, [4.5, 9.0, 9.0])
rule1 = ctrl.Rule( Glycaemia['poor'] | Sirolimus['poor'],  Proteinuria['low'])
rule2 = ctrl.Rule(Sirolimus['average'],  Proteinuria['medium'])
rule3 = ctrl.Rule(Sirolimus['good'] |  Glycaemia['good'],  Proteinuria['high'])

Proteinuria_op_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
Proteinuria_op = ctrl.ControlSystemSimulation(Proteinuria_op_ctrl)
Proteinuria_op.input['Glycaemia'] = 1.3
Proteinuria_op.input['Sirolimus'] = 36.7

Proteinuria_op.compute()
print (Proteinuria_op.output['Proteinuria'])
Proteinuria.view(sim= Proteinuria_op)


Proteinuria.view(sim= Proteinuria_op)



pip install scikit-fuzzy