# -*- coding: utf-8 -*-
"""Fuzzy Logic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e61aFgzGwsK6XfAoYtl7Vw8uknT_67uI
"""

pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz 
import matplotlib.pyplot as plt
from skfuzzy import control as ctrl

x = np.arange(30,80.1,0.1)
slow= fuzz.trimf(x,[30,30,50])
medium = fuzz.trimf(x,[30,50,70])
medium_fast = fuzz.trimf(x,[50,60,80])
full_speed =  fuzz.trimf(x,[80,80,80])
plt.figure()
plt.plot(x, slow,'k', lineWidth=2, label='slow')
plt.plot(x, medium,'b', lineWidth=2, label='medium')
plt.plot(x, medium_fast,'r', lineWidth=2, label='medium_fast')
plt.plot(x, full_speed,'y', lineWidth=2, label='Full speed')

x = np.arange(10,80.1,0.1)
slow= fuzz.trapmf(x,[10,20,30,40])
medium = fuzz.trapmf(x,[10,30,50,55])
medium_fast = fuzz.trapmf(x,[10,50,60,80])
full_speed =  fuzz.trapmf(x,[80,90,100,110])
plt.figure()
plt.plot(x, slow,'k', lineWidth=2, label='slow')
plt.plot(x, medium,'b', lineWidth=2, label='medium')
plt.plot(x, medium_fast,'r', lineWidth=2, label='medium_fast')
plt.plot(x, full_speed,'y', lineWidth=2, label='Full speed')
plt.xlabel("Toc do (km/h)")
plt.ylabel("Ham lien thoa")

x = np.arange(0,300.1,0.1)
slow= fuzz.gaussmf(x,140,50)
medium = fuzz.gaussmf(x,150,60)
medium_fast = fuzz.gaussmf(x,170,80)
full_speed =  fuzz.gaussmf(x,190,100)

plt.figure()
plt.plot(x, slow,'k', lineWidth=2, label='slow')
plt.plot(x, medium,'b', lineWidth=2, label='medium')
plt.plot(x, medium_fast,'r', lineWidth=2, label='medium_fast')
plt.plot(x, full_speed,'y', lineWidth=2, label='Full speed')

x=np.arange(0,100.1,0.1)
slow= fuzz.membership.gbellmf(x, 3, 3, 10)
medium= fuzz.membership.gbellmf(x, 4, 3, 20)
medium_fast= fuzz.membership.gbellmf(x, 4, 5, 15)
full_speed= fuzz.membership.gbellmf(x, 5, 4, 22)
plt.plot(x, slow,'r', lineWidth=2, label='slow')
plt.plot(x, medium,'k', lineWidth=2, label='medium')
plt.plot(x, full_speed,'y', lineWidth=2, label='full_speed')
plt.plot(x, medium_fast,'b', lineWidth=2, label='full_speed')

low =  fuzz.membership.sigmf(x, 50, 2)
medium = fuzz.membership.sigmf(x,50,12)
medium_fast = fuzz.membership.sigmf(x,70,3)
full_speed = fuzz.membership.sigmf(x,45,22)
plt.plot(x, slow,'r', lineWidth=2, label='slow')
plt.plot(x, medium,'k', lineWidth=2, label='medium')
plt.plot(x, full_speed,'y', lineWidth=2, label='medium_fast')
plt.plot(x, medium_fast,'b', lineWidth=2, label='full_speed')

food = ctrl.Antecedent(np.arange(0,11,1),'food');
service = ctrl.Antecedent(np.arange(0,11,1),'service')
tip = ctrl.Antecedent(np.arange(10,26,1),'tip')
food.automf(3)
service.automf(3)
tip['low'] = fuzz.trimf(tip.universe, [0, 0, 13])
tip['medium'] = fuzz.trimf(tip.universe, [0, 13, 25])
tip['high'] = fuzz.trimf(tip.universe, [13, 25, 25])

rule1 = ctrl.Rule(food['poor']|service['poor'],tip['low'])
rule2 = ctrl.Rule(food['average']|service['average'],tip['medium'])
rule3 = ctrl.Rule(food['good']|service['good'],tip['high'])

tiping_ctrl = ctrl.ControlSystem([rule1,rule2,rule3])
tiping = ctrl.ControlSystemSimulation(tiping_ctrl)
tiping.input['food'] = 6.5
tiping.input['service']=9.8
tiping.compute()
print(tiping.output['tip'])