# -*- coding: utf-8 -*-
"""Medical_Diagnosis_System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17C23-DAUCrgbnBxbLF8gCmfMwojHHu0J
"""

pip install scikit-fuzzy