# -*- coding: utf-8 -*-
"""Nutritional_Needs_Recommendation .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eWvui7GAysH7yOGVp0EV_U1a00cpdD_3
"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl


height = ctrl.Antecedent(np.arange(93, 110, 1), 'height')
weight = ctrl.Antecedent(np.arange(46, 55, 1), 'weight')
mem = ctrl.Consequent(np.arange(0, 201, 1), 'mem')

height.automf(3)
weight.automf(3)

mem['low'] = fuzz.trimf(mem.universe, [0, 0, 100])
mem['medium'] = fuzz.trimf(mem.universe, [0, 100, 200])
mem['high'] = fuzz.trimf(mem.universe, [100, 200, 200])
rule1 = ctrl.Rule(height['poor'] | weight['poor'], mem['low'])
rule2 = ctrl.Rule(weight['average'], mem['medium'])
rule3 = ctrl.Rule(weight['good'] | height['good'], mem['high'])

membership_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
membership = ctrl.ControlSystemSimulation(membership_ctrl)
membership.input['height'] = 98
membership.input['weight'] = 56


membership.compute()
print (membership.output['mem'])
mem.view(sim=membership)